'use strict';

const REDOU_CODEX_ERROR_CODES = Object.freeze({
  EXECUTABLE_NOT_FOUND: 'REDOU_CODEX_RUNTIME_NOT_FOUND',
  START_FAILED: 'REDOU_CODEX_START_FAILED',
  MODEL_CONFIG_MISSING: 'REDOU_MODEL_CONFIG_MISSING',
  PROTOCOL_ERROR: 'REDOU_CODEX_PROTOCOL_ERROR',
  TIMEOUT: 'REDOU_CODEX_TIMEOUT',
  UNKNOWN: 'REDOU_CODEX_UNKNOWN',
});

module.exports = { REDOU_CODEX_ERROR_CODES };
